defaults: &defaults
  # 'qm' refers to 'Question Market' aka the question bank
  qm_api_url: "http://localhost:3001/"
  devise_mailer_sender: "askup@example.com"
  limit_question_index_to_users_questions_only: "true"
  mail_host_address: "mailhost.com"
  mail_host_port: "587"
  mail_host_username: "username"
  mail_host_password: "password"

development:
  analytics_log_file: "/log/development_analytics.log"
  <<: *defaults

test:
  analytics_log_file: "/log/test_analytics.log"
  <<: *defaults

staging:
  analytics_log_file: "/log/staging_analytics.log"
  <<: *defaults

production:
  analytics_log_file: "/log/production_analytics.log"
  <<: *defaults
