defaults: &defaults
  # 'qm' refers to 'Question Market' aka the question bank
  qm_port: "3002"
  qm_base_url: "http://localhost"
  qm_api_url: "http://localhost:3000/"

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
