defaults: &defaults
  # 'qm' refers to 'Question Market' aka the question bank
  qm_api_url: "http://localhost:3000/"
  devise_mailer_sender: "askup@example.com"

development:
  analytics_log_file: "/log/development_analytics.log"
  <<: *defaults

test:
  analytics_log_file: "/log/test_analytics.log"
  <<: *defaults

pilot:
  analytics_log_file: "/log/pilot_analytics.log"
  <<: *defaults

production:
  analytics_log_file: "/log/production_analytics.log"
  <<: *defaults
